easy_admin:

  
  site_name: "HSE Panel Admin"


  edit:
    actions:
      - { name: 'show', css_class: "btn btn-outline-primary" }
    title: Edition


  list:
    title: 'Liste des %%entity_label%%'
    actions:
      - { name: 'new', label: "Ajouter %%entity_label%%"}
      - { name: 'show', icon: 'search' , label: ''}
      - { name: 'edit', label: "Modifier" }
      - { name: 'delete', label: "Supprimer" }



  design:
    menu:


      - { label: 'Acceuil', url: 'http://localhost:8000', rel: 'index', icon: 'home' }
      - { label: 'Dashboard', url: 'http://localhost:8000', rel: 'index', icon: 'chart-pie' }


      - { label: "Entities"}
      - label: "Produits"
        icon: "flask"
        permission: ['ROLE_ADMIN', 'ROLE_MOD', 'ROLE_MOD_PRODUCTS']
        children:
          - {entity: Product, label: 'Liste de Produits', icon: 'th-list'}
          - {entity: Product, label: 'Ajouter Produit', icon: 'plus', params: {action: 'new'}}



      - label: "Groupes"
        icon: 'users'
        permission: ['ROLE_ADMIN', 'ROLE_MOD', 'ROLE_MOD_GROUPS']
        children:
          - {entity: Department, label: 'Liste des Groupes', icon: 'th-list'}
          - {entity: Department, label: 'Ajouter Groupe', icon: 'plus', params: {action: 'new'}}



      - label: "Conseil de Prudence"
        icon: "exclamation-circle"
        permission: ['ROLE_ADMIN']
        children:
          - {entity: ConseilPrudence, label: 'Liste de Conseils', icon: 'th-list'}
          - {entity: ConseilPrudence, label: 'Ajouter Conseil', icon: 'plus', params: {action: 'new'}}

          
      - label: "Mention de Danger"
        icon: "exclamation-triangle"
        permission: ['ROLE_ADMIN']
        children:
          - {entity: MentionDanger, label: 'Liste Mention de Danger', icon: 'th-list'}
          - {entity: MentionDanger, label: 'Ajouter Mention de Danger', icon: 'plus', params: {action: 'new'}}

          
      - label: "Pictogrammes"
        icon: "radiation"
        permission: ['ROLE_ADMIN']
        children:
          - {entity: Pictogramme, label: 'Liste de Pictogrammes', icon: 'th-list'}
          - {entity: Pictogramme, label: 'Ajouter Pictogramme', icon: 'plus', params: {action: 'new'}}

      - label: "Rapport"
        permission: ['ROLE_ADMIN', 'ROLE_MOD']
        children:
          - {entity: Report, label: 'Liste des Rapports', icon: 'th-list'}
          - {entity: Report, label: 'Ajouter Rapport', icon: 'plus', params: {action: 'new'}}


      - label: "EPI"
        icon: "glasses"
        permission: ['ROLE_ADMIN']
        children:
          - {entity: Protection, label: 'Liste des EPI', icon: 'th-list'}
          - {entity: Protection, label: 'Ajouter EPI', icon: 'plus', params: {action: 'new'}}

      - { label: "Gestion des Utilisateurs", permission: ROLE_ADMIN}


      - label: "Utilisateur"
        icon: "user"
        permission: ['ROLE_ADMIN', 'ROLE_MOD_USERS']
        children:
          - {entity: User, label: "Liste d'Utilisatuer", icon: 'th-list'}
          - {entity: User, label: 'Ajouter Utilisateur', icon: 'plus', params: {action: 'new'}}




  entities:


    User:

      label: "Utilisateurs"
      class: App\Entity\User
      controller: App\Controller\UserController

      list:
        title: "Liste d'utilisateurs"
        item_permission: ['ROLE_ADMIN', 'ROLE_MOD', 'ROLE_MOD_USERS']
        batch_actions: ['delete']
        filters: [{ property: 'roles', label: 'Roles'}, { property: 'department', label: 'Groupes'}]
        fields:
          - { property: 'userName', label: "Nom d'utilisateur" }
          - { property: 'fullName', label: "Nom et Prénom" }
          - { property: 'roles', template: 'admin/roles/show.html.twig'}
          - { property: 'department', label: "Groupe", template: 'admin/user/groupField.html.twig' }
      
      new:
        title: 'Ajouter Nouvel Utilisateur'
        item_permission: ['ROLE_ADMIN', 'ROLE_MOD_USERS']
      edit:
        fields: ['-password']
      show:
        fields:
          - { property: 'userName', label: "Nom d'utilisateur", type: 'text'}
          - { property: 'fullName', label: "Nom et Prénom" }
          - { property: 'department', label: "Département" }
          - { property: 'roles', label: "Roles", template: 'admin/roles/show.html.twig' }
          - adresse
          


      form:
        fields:
          - { type: 'tab', label: 'Informations de base', icon: 'clipboard'}
          - { property: 'userName', label: "Nom d'utilisateur", type: 'text'}
          - { property: 'lastName', label: "Nom", type: 'text' }
          - { property: 'firstName', label: "Prénom", type: 'text' }
          - { property: 'password', label: "Mot de passe", type: 'password'}
          - { property: 'roles', label: "Administrateur", type: 'choice', permission: 'ROLE_ADMIN', type_options: { multiple: true, expanded: true, mapped: true, choices: {' ': 'ROLE_ADMIN'} } }
          - { property: 'department', label: 'group'}
          - { type: 'tab', label: 'Coordonnées', icon: 'phone'}
          - { type: 'group', column: 6}
          - { property: "adresse", label: "Adresse", type: 'App\Form\AdresseType', type_options: { by_reference: true}}



      
    Product:

      label: "Produits"
      title: "Ajouter Produit"
      class: App\Entity\Product

      list:
        batch_actions: ['delete']
        item_permission: ['ROLE_ADMIN', 'ROLE_MOD', 'ROLE_MOD_PRODUCTS']
        sort: ['productCode', 'ASC']
        fields:
          - { property: 'productCode', label: 'Code Produit', type: 'text'}
          - { property: 'productName', label: 'Nom Produit', type: 'text'}
          - { property: 'fournisseur'}
          - { property: 'numeroUrgence', label: "Numéro d'urgene", type: 'tel'}
          - { property: 'fiche', type: 'file', template: 'admin/fiche/show.html.twig', label: 'Fiche de données de sécurité' , base_path: '%app.path.fiches%'}

      new:
        title: 'Ajouter Nouveau Produit'
      show:
        title: "%%entity_name%%"
        fields:
          - { property: 'productCode', label: 'Code Produit'}
          - { property: 'productName', label: 'Nom Produit'}
          - { property: 'fiche', template: 'admin/fiche/show.html.twig', base_path: '%app.path.fiches%'}
          - { property: 'fournisseur'}
          - { property: 'adresseFournisseur', label: 'Adresse du Fournisseur'}
          - { property: 'numeroUrgence', label: "Numéro d'urgene", type: 'tel'}
          - { property: 'conseil', label: "Conseils de Prudence"}
          - { property: 'mentionDangers', label: "Mentions de Danger"}
          - { property: 'pictogramme', label: 'Pictrogrammes', template: 'admin/pictogrammes/show.html.twig'}
          - { property: 'protection', label: 'Equipement de protection individuel', template: 'admin/protection/show.html.twig'}
          - { property: 'premiersSecours', label: ' ', template: 'admin/premiers secours/show.html.twig'}

      form:
        fields:
          - { type: 'tab', label: 'Informations de base', icon: 'clipboard'}
          - { property: 'productName', label: 'Nom Produit'}
          - { property: 'productCode', label: 'Code Produit'}
          - { property: 'numeroUrgence', label: "Numéro d'urgence", type: 'tel'}
          - { property: 'ficheFile', type: 'vich_file', label: 'Fiche de données de sécurité', help: '(Ajouter la fiche de données de sécurité en format PDF)' }
          - { type: 'tab' ,label: 'Securité', icon: 'lock'}
          - { type: 'group', columns: 6, label: 'Messages' }
          - { property: 'conseil', label: "Conseils", type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { property: 'mentionDangers', label: "Dangers", type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { type: 'group', columns: 6, label: 'Pictogrammes' }
          - { property: 'pictogramme', label: 'Pictogrammes', type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { property: 'protection', label: 'Equipenet de protection individuel', type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { type: 'tab', label: "Premiers Secours", icon: 'first-aid'}
          - { type: 'group', label: ' ', css_class: 'w-100'}
          - { property: 'premiersSecours', label: ' ', type: 'App\Form\PremiersSecoursType'}
          - { type: 'tab', label: "Fournisseur", icon: 'truck'}
          - { type: 'group', columns: 6, label: ' ' }
          - { property: "fournisseur", label: " ", type: 'App\Form\FournisseurType', type_options: { by_reference: true}}
          - { type: 'group', columns: 6, label: ' ' }
          - { property: "adresseFournisseur", label: " ", type: 'App\Form\AdresseType', type_options: { by_reference: true}}




    Department:

      label: "Departements"
      class: App\Entity\Department
      controller: App\Controller\GroupController

      list:
        title: 'Liste des Groupes'
        item_permission: ['ROLE_ADMIN', 'ROLE_MOD', 'ROLE_MOD_GROUPS']
        actions:
          - { name: 'new', label: 'Ajouter un groupe'}
        batch_actions: ['delete']
        fields:
          - { property: 'departmentName', label: 'Nom du Groupe', type: 'text'}
          - { property: 'administrator', label: 'Administrateur'}
          - { property: 'moderator', label: 'Modérateur'}
          - { property: 'canManageUsers', label: "Mod Utilisateur"}
          - { property: 'canManageProducts', label: "Mod Produits"}
          - { property: 'canManageGroups', label: "Mod Groupes"}
          - { property: 'canManageStock', label: "Mod Stock"}
        

      new:
        title: 'Ajouter Nouveau Groupe'

      form:
        fields:
          - { type: 'tab', label: 'Permissions'}
          - { property: 'departmentName', label: 'Nom du groupe', type: text }
          - { property: 'manager', type_options: {by_reference: true}}
          - { property: 'employees', label: 'Membre(s)', type_options: { by_reference: false }}
          - { type: 'tab', label: 'Options Avancées'}
          - { type: 'group', columns: 6,  label: 'Users'}
          - { type: 'group', columns: 6,  label: 'Products'}
          - { type: 'group', columns: 6,  label: 'Groups'}
          - { type: 'group', columns: 6,  label: 'Stock'}
          





    ConseilPrudence:

      label: 'Conseils de Prudence'
      class: App\Entity\ConseilPrudence

      list:
        item_permission: ['ROLE_ADMIN']
        sort: ['code', 'ASC']
        fields:
          - code
          - { property: 'text', label: 'Message'} 
        batch_actions: ['delete']

      new:
        title: 'Ajouter Nouveau Conseil'
      form:
        fields:
          - code
          - text

      show:
        fields:
          - code
          - text

      

    Pictogramme:

      label: 'Pictogrammes'
      class: App\Entity\Pictogramme
      disabled_actions: ['delete', 'show', 'search']
      list:
        item_permission: ['ROLE_ADMIN']
        sort: ['code', 'ASC']
        fields:
          - { property: 'code', label: 'Code'}
          - { property: 'text', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.pictograms_images%'}
      
      new:
        title: 'Ajouter Nouveau Pictogramme'

      show:
        fields:
          - { property: 'code', label: 'Code'}
          - { property: 'text', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.pictograms_images%'}
      form:
        fields:
          - { property: 'code', label: 'Code'}
          - { property: 'text', label: 'Message'}
          - { property: 'imageFile', type: 'vich_image' }



    MentionDanger:

      label: 'Mention de Danger'
      class: App\Entity\MentionDanger

      list:
        item_permission: ['ROLE_ADMIN']
        sort: ['code', 'ASC']
        fields:
          - code
          - { property: 'text', label: 'Message'} 
        batch_actions: ['delete']

      new:
        title: 'Ajouter Nouvel Mention'

      form:
        fields:
          - code
          - text

      show:
        fields:
          - code
          - text


    Report:

      label: 'Rapports'
      class: App\Entity\Report
      controller: App\Controller\ReportController


      list:
        batch_actions: ['delete']
        sort: ['createdAt', 'DESC']
        item_permission: ['ROLE_ADMIN']
        filters: ['type', { property: 'createdAt', label: 'Date de création'}]
        fields:
          - { property: 'title', label: 'Titre'}
          - type
          - { property: 'createdAt', label: 'Date de création', format: 'd/m/Y H:i:s'}
          - { property: 'author', label: 'Auteur' }
          - { property: 'file', type: 'file', template: 'admin/rapport/show.html.twig', label: 'Rapport' , base_path: '%app.path.reports%'}


      form:
        fields:
          - { property: 'title', label: 'Titre'}
          - type
          - { property: 'content', label: ' ', type: "text_editor"}
          - { property: 'reportFile', type: 'vich_file', label: 'Rapport', help: '(Ajouter le rapport en format PDF)' }

      show:
        fields:
          - { property: 'title', label: 'Titre'}
          - { property: 'createdAt', label: 'date de Création'}
          - { property: 'content', label: ' ', type: "raw"}
          - { property: 'file', template: 'admin/rapport/show.html.twig', base_path: '%app.path.reports%'}



    Protection:

      label: 'Equipement de Protection Individuel'
      class: App\Entity\Protection


      show:
        fields:
          - { property: 'name', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.protection_images%' }

      new:
        title: 'Ajouter Nouveau équipement de protection'

      list:
        item_permission: ['ROLE_ADMIN']
        fields:
          - { property: 'name', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.protection_images%' }


      form:
        fields:
          - { property: 'name', label: 'Message'}
          - { property: 'imageFile', type: 'vich_image' }