easy_admin:
  site_name: "HSE Panel Admin"
  edit:
    actions:
      - { name: 'show', css_class: "btn btn-outline-primary" }
  design:
    menu:
      - { label: 'Homepage', url: 'http://localhost:8000', rel: 'index', icon: 'home' }
      - { label: "Entities"}
      - label: "Products"
        children:
          - {entity: Product, label: 'Products List', icon: 'th-list'}
          - {entity: Product, label: 'Add New Product', icon: 'plus', params: {action: 'new'}}
      - label: "Departements"
        children:
          - {entity: Department, label: 'Departments List', icon: 'th-list'}
          - {entity: Department, label: 'Add New Department', icon: 'plus', params: {action: 'new'}}
      - label: "Conseil de Prudence"
        children:
          - {entity: ConseilPrudence, label: 'Liste de Conseil', icon: 'th-list'}
          - {entity: ConseilPrudence, label: 'Ajouter Conseil', icon: 'plus', params: {action: 'new'}}
      - label: "Mention de Danger"
        children:
          - {entity: MentionDanger, label: 'Liste de Conseil', icon: 'th-list'}
          - {entity: MentionDanger, label: 'Ajouter Conseil', icon: 'plus', params: {action: 'new'}}
      - { label: "User Managment", permission: ROLE_ADMIN}
      - label: "Users"
        permission: ROLE_ADMIN
        children:
          - {entity: User, label: 'Users List', icon: 'th-list'}
          - {entity: User, label: 'Add New User', icon: 'plus', params: {action: 'new'}}
  entities:
    User:
      label: "Users"
      class: App\Entity\User
      list:
        title: 'user'
        item_permission: 'ROLE_ADMIN'
        fields:
          - userName
          - firstName
          - roles
          - department
          - { property: 'loginStatus', label: 'Online', type: 'boolean' }
      form:
        fields:
          - { property: 'userName', type: 'text'}
          - { property: 'firstName', type: 'text' }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, mapped: true, choices: { 'User': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN', 'Moderateur Securité': 'ROLE_MOD_S', 'Moderateur Environnement': 'ROLE_MOD_E','Moderateur Hygiéne': 'ROLE_MOD_H','Gestionnaire de Stock': 'ROLE_GES_STOCK'} } }
          - { property: 'department'}
      controller: App\Controller\UserController
    Product:
      label: "Products"
      title: "Ajouter Produit"
      class: App\Entity\Product
      form:
        fields:
          - { type: 'tab', label: 'Informations'}
          - { type: 'group', columns: 12, label: 'Informations' }
          - productName
          - productCode
          - { property: 'numeroUrgence', label: "Numéro d'urgence", type: 'tel'}
          - { property: 'conseil', label: "Conseils", type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { property: 'mentionDangers', label: "Dangers", type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { type: 'tab', label: "Fournisseur"}
          - { type: 'group', columns: 6, label: ' ' }
          - { property: "fournisseur", label: " ", type: 'App\Form\FournisseurType', type_options: { by_reference: true}}
          - { type: 'group', columns: 6, label: ' ' }
          - { property: "adresseFournisseur", label: " ", type: 'App\Form\AdresseType', type_options: { by_reference: true}}
    Department:
      label: "Departments"
      class: App\Entity\Department
      form:
        fields:
          - { property: 'departmentName', label: 'Nom du département', type: text }
          - { property: 'manager', type_options: {by_reference: true}}
          - { property: 'employees', type_options: { by_reference: false }}
    ConseilPrudence:
      label: 'Conseils de Prudence'
      class: App\Entity\ConseilPrudence
      list:
        fields:
          - code
          - text
      form:
        fields:
          - code
          - text
      show:
        fields:
          - code
          - text
    MentionDanger:
      label: 'Mention de Danger'
      class: App\Entity\MentionDanger
      list:
        fields:
          - code
          - text
      form:
        fields:
          - code
          - text
      show:
        fields:
          - code
          - text
