easy_admin:

  
  site_name: "HSE Panel Admin"


  edit:
    actions:
      - { name: 'show', css_class: "btn btn-outline-primary" }

  list:
    actions:
      - { name: 'new', label: "Ajouter %%entity_label%%" }
      - { name: 'show', icon: 'search' , label: ''}
      - { name: 'edit', label: "Modifier" }
      - { name: 'delete', label: "Supprimer" }



  design:
    menu:


      - { label: 'Acceuil', url: 'http://localhost:8000', rel: 'index', icon: 'home' }
      - { label: 'Dashboard', url: 'http://localhost:8000', rel: 'index', icon: 'shart' }


      - { label: "Entities"}
      - label: "Produits"
        icon: "flask"
        children:
          - {entity: Product, label: 'Liste de Produits', icon: 'th-list'}
          - {entity: Product, label: 'Ajouter Produit', icon: 'plus', params: {action: 'new'}}



      - label: "Groupes"
        icon: 'users'
        children:
          - {entity: Department, label: 'Liste des Groupes', icon: 'th-list'}
          - {entity: Department, label: 'Ajouter Groupe', icon: 'plus', params: {action: 'new'}}



      - label: "Conseil de Prudence"
        icon: "exclamation-circle"
        children:
          - {entity: ConseilPrudence, label: 'Liste de Conseils', icon: 'th-list'}
          - {entity: ConseilPrudence, label: 'Ajouter Conseil', icon: 'plus', params: {action: 'new'}}

          
      - label: "Mention de Danger"
        icon: "exclamation-triangle"
        children:
          - {entity: MentionDanger, label: 'Liste Mention de Danger', icon: 'th-list'}
          - {entity: MentionDanger, label: 'Ajouter Mention de Danger', icon: 'plus', params: {action: 'new'}}

          
      - label: "Pictogrammes"
        icon: "radiation"
        children:
          - {entity: Pictogramme, label: 'Liste de Pictogrammes', icon: 'th-list'}
          - {entity: Pictogramme, label: 'Ajouter Pictogramme', icon: 'plus', params: {action: 'new'}}

      - label: "Rapport"
        children:
          - {entity: Report, label: 'Liste des Rapports', icon: 'th-list'}
          - {entity: Report, label: 'Ajouter Rapport', icon: 'plus', params: {action: 'new'}}


      - label: "EPI"
        children:
          - {entity: Protection, label: 'Liste des EPI', icon: 'th-list'}
          - {entity: Protection, label: 'Ajouter EPI', icon: 'plus', params: {action: 'new'}}

      - { label: "Gestion des Utilisateurs", permission: ROLE_ADMIN}


      - label: "Utilisateur"
        icon: "user"
        permission: ROLE_ADMIN
        children:
          - {entity: User, label: "Liste d'Utilisatuer", icon: 'th-list'}
          - {entity: User, label: 'Ajouter Utilisateur', icon: 'plus', params: {action: 'new'}}




  entities:


    User:

      label: "Utilisateurs"
      class: App\Entity\User
      controller: App\Controller\UserController

      list:
        title: 'Utilisateurs'
        item_permission: 'ROLE_ADMIN'
        batch_actions: ['delete']
        filters: ['username', 'department']
        fields:
          - { property: 'userName', label: "Nom d'utilisateur" }
          - { property: 'fullName', label: "Nom et Prénom" }
          - { property: 'roles', , template: 'admin/roles/show.html.twig'}
          - grade
          - { property: 'department', label: "Département" }
          - { property: 'loginStatus', label: 'En ligne', type: 'boolean' }
      

      edit:
        fields: ['-password']
      show:
        fields:
          - { property: 'userName', label: "Nom d'utilisateur", type: 'text'}
          - { property: 'fullName', label: "Nom et Prénom" }
          - { property: 'department', label: "Département" }
          - grade
          - { property: 'roles', label: "Roles", template: 'admin/roles/show.html.twig' }
          - adresse
          


      form:
        fields:
          - { type: 'tab', label: 'Informations de base', icon: 'clipboard'}
          - { property: 'userName', label: "Nom d'utilisateur", type: 'text'}
          - { property: 'lastName', label: "Nom", type: 'text' }
          - { property: 'firstName', label: "Prénom", type: 'text' }
          - password
          - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: true, mapped: true, choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN', 'Moderateur Securité': 'ROLE_MOD_S', 'Moderateur Environnement': 'ROLE_MOD_E','Moderateur Hygiéne': 'ROLE_MOD_H','Ressource Humaine': 'ROLE_RH', 'Gestionnaire de Stock': 'ROLE_GES_STOCK'} } }
          - grade
          - { property: 'department', label: 'group'}
          - { type: 'tab', label: 'Coordonnées', icon: 'phone'}
          - { type: 'group', column: 6}
          - { property: "adresse", label: " ", type: 'App\Form\AdresseType', type_options: { by_reference: true}}



      
    Product:

      label: "Produits"
      title: "Ajouter Produit"
      class: App\Entity\Product

      list:
        batch_actions: ['delete']
        sort: ['productCode', 'ASC']
        fields:
          - { property: 'productCode', label: 'Code Produit', type: 'text'}
          - { property: 'productName', label: 'Nom Produit', type: 'text'}
          - { property: 'fournisseur'}
          - { property: 'numeroUrgence', label: "Numéro d'urgene", type: 'tel'}
          - { property: 'fiche', typ: 'file', template: 'admin/fiche/show.html.twig', label: 'Fiche de données de sécurité' , base_path: '%app.path.fiches%'}

      show:
        title: "%%entity_name%%"
        fields:
          - { property: 'productCode', label: 'Code Produit'}
          - { property: 'productName', label: 'Nom Produit'}
          - { property: 'fiche', template: 'admin/fiche/show.html.twig', base_path: '%app.path.fiches%'}
          - { property: 'fournisseur'}
          - { property: 'adresseFournisseur', label: 'Adresse du Fournisseur'}
          - { property: 'numeroUrgence', label: "Numéro d'urgene", type: 'tel'}
          - { property: 'conseil', label: "Conseils de Prudence"}
          - { property: 'mentionDangers', label: "Mentions de Danger"}
          - { property: 'pictogramme', label: 'Pictrogrammes', template: 'admin/pictogrammes/show.html.twig'}
          - { property: 'protection', label: 'Equipement de protection individuel', template: 'admin/protection/show.html.twig'}
          - { property: 'premiersSecours', label: ' ', template: 'admin/premiers secours/show.html.twig'}

      form:
        fields:
          - { type: 'tab', label: 'Informations de base', icon: 'clipboard'}
          - { property: 'productName', label: 'Nom Produit'}
          - { property: 'productCode', label: 'Code Produit'}
          - { property: 'numeroUrgence', label: "Numéro d'urgence", type: 'tel'}
          - { property: 'ficheFile', type: 'vich_file', label: 'Fiche de données de sécurité', help: '(Ajouter la fiche de données de sécurité en format PDF)' }
          - { type: 'tab' ,label: 'Securité', icon: 'lock'}
          - { type: 'group', columns: 6, label: 'Messages' }
          - { property: 'conseil', label: "Conseils", type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { property: 'mentionDangers', label: "Dangers", type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { type: 'group', columns: 6, label: 'Pictogrammes' }
          - { property: 'pictogramme', label: 'Pictogrammes', type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { property: 'protection', label: 'Equipenet de protection individuel', type: 'easyadmin_autocomplete', type_options: { by_reference: false}}
          - { type: 'tab', label: "Premiers Secours", icon: 'first-aid'}
          - { type: 'group', label: ' ', css_class: 'w-100'}
          - { property: 'premiersSecours', label: ' ', type: 'App\Form\PremiersSecoursType'}
          - { type: 'tab', label: "Fournisseur", icon: 'truck'}
          - { type: 'group', columns: 6, label: ' ' }
          - { property: "fournisseur", label: " ", type: 'App\Form\FournisseurType', type_options: { by_reference: true}}
          - { type: 'group', columns: 6, label: ' ' }
          - { property: "adresseFournisseur", label: " ", type: 'App\Form\AdresseType', type_options: { by_reference: true}}




    Department:

      label: "Departements"
      class: App\Entity\Department

      list:
        batch_actions: ['delete']
        fields:
          - { property: 'departmentName', label: 'Nom Departement', type: 'text'}
          - { property: 'canManageUsers', label: "Gestion d'Utilisateur"}
          - { property: 'canManageProducts', label: "Gestion de Produits"}
          - { property: 'canManageGroups', label: "Gestion de Groupes"}
          - { property: 'canManageStock', label: "Gestion de Stock"}
        

      form:
        fields:
          - { type: 'tab', label: 'Permissions'}
          - { property: 'departmentName', label: 'Nom du département', type: text }
          - { property: 'manager', type_options: {by_reference: true}}
          - { property: 'employees', type_options: { by_reference: false }}
          - { property: 'canManageUsers', label: "Gestion d'Utilisateur"}
          - { property: 'canManageProducts', label: "Gestion de Produits"}
          - { property: 'canManageGroups', label: "Gestion de Groupes"}
          - { property: 'canManageStock', label: "Gestion de Stock"}
          - { type: 'tab', label: 'Options Avancées'}
          - { type: 'group', columns: 6,  label: 'Users'}
          - { type: 'group', columns: 6,  label: 'Products'}
          - { type: 'group', columns: 6,  label: 'Groups'}
          - { type: 'group', columns: 6,  label: 'Stock'}
          





    ConseilPrudence:

      label: 'Conseils de Prudence'
      class: App\Entity\ConseilPrudence

      list:
        title: "Conseils de Prudence"
        sort: ['code', 'ASC']
        fields:
          - code
          - { property: 'text', label: 'Message'} 
        batch_actions: ['delete']

      form:
        fields:
          - code
          - text

      show:
        fields:
          - code
          - text

      

    Pictogramme:

      label: 'Pictogrammes'
      class: App\Entity\Pictogramme
      disabled_actions: ['delete', 'show', 'search']
      list:
        sort: ['code', 'ASC']
        fields:
          - { property: 'code', label: 'Code'}
          - { property: 'text', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.pictograms_images%'}
      show:
        fields:
          - { property: 'code', label: 'Code'}
          - { property: 'text', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.pictograms_images%'}
      form:
        fields:
          - { property: 'code', label: 'Code'}
          - { property: 'text', label: 'Message'}
          - { property: 'imageFile', type: 'vich_image' }



    MentionDanger:

      label: 'Mention de Danger'
      class: App\Entity\MentionDanger

      list:
        title: "Mention de Danger"
        sort: ['code', 'ASC']
        fields:
          - code
          - { property: 'text', label: 'Message'} 
        batch_actions: ['delete']

      form:
        fields:
          - code
          - text

      show:
        fields:
          - code
          - text


    Report:

      label: 'Rapports'
      class: App\Entity\Report


      list:
        fields:
          - { property: 'title', label: 'Titre'}
          - { property: 'createdAt', label: 'date de Création'}


      form:
        fields:
          - { property: 'title', label: 'Titre'}
          - { property: 'content', label: ' ', type: "text_editor"}

      show:
        fields:
          - { property: 'title', label: 'Titre'}
          - { property: 'createdAt', label: 'date de Création'}
          - { property: 'content', label: ' ', type: "raw"}


    Protection:

      label: 'Equipement de Protection Individuel'
      class: App\Entity\Protection


      show:
        fields:
          - { property: 'name', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.protection_images%' }

      list:
        fields:
          - { property: 'name', label: 'Message'}
          - { property: 'image', type: 'image', base_path: '%app.path.protection_images%' }


      form:
        fields:
          - { property: 'name', label: 'Message'}
          - { property: 'imageFile', type: 'vich_image' }