vich_uploader:
    db_driver: orm

    mappings:
      pictograms_images:
        uri_prefix: '%app.path.pictograms_images%'
        upload_destination: '%kernel.project_dir%/public%app.path.pictograms_images%'

      protection_images:
        uri_prefix: '%app.path.protection_images%'
        upload_destination: '%kernel.project_dir%/public%app.path.protection_images%'


      fiches:
        uri_prefix: '/uploads/files/fiches'
        upload_destination: '%kernel.project_dir%/public/uploads/files/fiches'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      reports:
        uri_prefix: '/uploads/files/reports'
        upload_destination: '%kernel.project_dir%/public/uploads/files/reports'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      workingZones_images:
        uri_prefix: '%app.path.workingZones_images%'
        upload_destination: '%kernel.project_dir%/public%app.path.workingZones_images%'
