vich_uploader:
    db_driver: orm

    mappings:
      pictograms_images:
        uri_prefix: '%app.path.pictograms_images%'
        upload_destination: '%kernel.project_dir%/public%app.path.pictograms_images%'